# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import random
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap, QPainter
from PyQt5.QtWidgets import QWidget, QApplication, QMainWindow


class Ui_MainWindow(QWidget):

    def __init__(self):
        super().__init__()
        self.paintBool = True
        self.rotationVar = 0
        self.MainWindow = QMainWindow()
        self.winW = 500
        self.winH = 500
        self.initUI()
        self.setupUi()


    def initUI(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.setGeometry(100, 50, self.winW, self.winH)
        self.MainWindow.setMaximumSize(QtCore.QSize(self.winW, self.winH))
        self.MainWindow.show()

        self.centralwidget = QtWidgets.QWidget(self.MainWindow)

        self.lbl = QtWidgets.QLabel(self.centralwidget)
        self.lbl.resize(self.winW, self.winH)
        pixmap = QPixmap(self.winW, self.winH)
        self.lbl.setPixmap(pixmap)

        self.MainWindow.setCentralWidget(self.centralwidget)

    def setupUi(self):
        self.echo = QPixmap('imgs/Echo.png')
        self.barra = QPixmap('imgs/Espejo.png')

        transform_1 = QtGui.QTransform()
        transform_1.rotate(45)
        transform_2 = QtGui.QTransform()
        transform_2.rotate(90)
        transform_3 = QtGui.QTransform()
        transform_3.rotate(135)
        transform_4 = QtGui.QTransform()
        transform_4.rotate(225)

        self.rotated_pixmap1 = self.barra.transformed(transform_1)
        self.rotated_pixmap2 = self.barra.transformed(transform_2)
        self.rotated_pixmap3 = self.barra.transformed(transform_3)
        self.rotated_pixmap4 = self.barra.transformed(transform_4)

        self.Button = QtWidgets.QPushButton("Rotar", self.centralwidget)
        self.Button.setGeometry(QtCore.QRect(0, 0, 60, 20))
        self.Button.clicked.connect(self.rotation)

        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 210, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 210, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 70, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 120, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 320, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 40, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 380, 47, 13))
        self.label_7.setObjectName("label_7")

        self.MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(self.MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        self.MainWindow.setMenuBar(self.menubar)

        self.menuEcho_Locator = QtWidgets.QMenu(self.menubar)
        self.menuEcho_Locator.setObjectName("menuEcho_Locator")


        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuEcho_Locator.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

        #PRUEBA
        qp = QPainter(self.lbl.pixmap())
        self.drawPoints(qp)
        self.drawPoints(qp)
        self.drawPoints(qp)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "Proyecto 2"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label.setPixmap(self.echo)
        self.label.resize(self.echo.width(), self.echo.height())
        self.label_2.setPixmap(self.barra)
        self.label_2.resize(self.barra.width(), self.barra.height())
        self.label_3.setPixmap(self.rotated_pixmap2)
        self.label_3.resize(self.rotated_pixmap2.width(), self.rotated_pixmap2.height())
        self.label_4.setPixmap(self.rotated_pixmap4)
        self.label_4.resize(self.rotated_pixmap4.width(), self.rotated_pixmap4.height())
        self.label_5.setPixmap(self.rotated_pixmap3)
        self.label_5.resize(self.rotated_pixmap3.width(), self.rotated_pixmap3.height())
        self.label_6.setPixmap(self.barra)
        self.label_6.resize(self.barra.width(), self.barra.height())
        self.label_7.setPixmap(self.rotated_pixmap1)
        self.label_7.resize(self.rotated_pixmap1.width(), self.rotated_pixmap1.height())
        self.menuEcho_Locator.setTitle(_translate("MainWindow", "Echo Locator"))

    def rotation(self):
        if self.rotationVar == 355:
            self.rotationVar = 0
        else:
            self.rotationVar += 5
        transform = QtGui.QTransform()
        transform.rotate(self.rotationVar)
        print(self.rotationVar)
        rotated = self.echo.transformed(transform)
        self.label.setPixmap(rotated)
        self.label.resize(rotated.width(), rotated.height())
        return

    def infront(self):
        pass

    # def keyPressEvent(self, event):
    #     gey = event.key()
    #     if gey == Qt.Key_M:
    #         self.paintBool = True
    #         self.update()
    #
    # def paintEvent(self, e):
    #     if self.paintBool:
    #         qp = QPainter(self.lbl.pixmap())
    #         self.drawPoints(qp)
    #         qp.end()

    def drawPoints(self, qp):
        pen = QtGui.QPen()
        pen.setWidth(3)
        pen.setColor(Qt.yellow)
        qp.setPen(pen)
        self.paintBool = False

        size = self.lbl.size()
        x = random.randint(1, size.width() - 1)
        y = random.randint(1, size.height() - 1)
        point = qp.drawPoint(x, y)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ui = Ui_MainWindow()
    sys.exit(app.exec_())